// Mechanics RPG v1.4.45 — dual UI mode: DDUI no-flicker default + proven chest-style ActionForm fallback; v3 safety retained.
// /scriptevent geumyi:subspace_ui ddui|chest switches the per-player UI mode without changing stored items.
// v1 legacy storage and v1.4.25 native chest carts are deliberately not destroyed/migrated.
import { world, system, ItemStack } from '@minecraft/server';
import { ActionFormData, CustomForm, ObservableBoolean, ObservableUIRawMessage, ObservableString } from '@minecraft/server-ui';
import { openLegacySubspace } from './subspace_legacy.js';

const ITEM='geumyi:subspace', COUNT=36, ACTIVE_COUNT=27;
const CUSTOM_STACKS=new Set(['geumyi:sheriff_bullet','geumyi:sheriff_bullet_bundle']);
const supportedId=id=>(id.startsWith('minecraft:')||id.startsWith('geumyi:'))&&id!=='geumyi:subspace';
const HEAD='geumyi:subspace_v3_head', STAGE='geumyi:subspace_v3_stage';
const JOURNAL='geumyi:subspace_v3_journal', LEGACY_CART='geumyi:subspace_v2_entity_id';
const LEGACY_POSITION='geumyi:subspace_v2_last_location';
const locks=new Set();
const UI_MODE_PROP='geumyi:subspace_ui_mode';

const ITEM_NAME_KO={
  sheriff_bullet:'리볼버 탄환', sheriff_bullet_bundle:'리볼버 탄환 6발 묶음', barrel:'통', noteblock:'소리 블록', jukebox:'주크박스',
  beehive:'벌통', dirt:'흙', grass_block:'잔디 블록', stone:'돌', cobblestone:'조약돌', andesite:'안산암', diorite:'섬록암', granite:'화강암',
  sand:'모래', red_sand:'붉은 모래', gravel:'자갈', clay:'점토', oak_log:'참나무 원목', spruce_log:'가문비나무 원목', birch_log:'자작나무 원목', jungle_log:'정글나무 원목',
  acacia_log:'아카시아나무 원목', dark_oak_log:'짙은 참나무 원목', mangrove_log:'맹그로브나무 원목', cherry_log:'벚나무 원목', oak_planks:'참나무 판자', spruce_planks:'가문비나무 판자',
  birch_planks:'자작나무 판자', jungle_planks:'정글나무 판자', acacia_planks:'아카시아나무 판자', dark_oak_planks:'짙은 참나무 판자', mangrove_planks:'맹그로브나무 판자', cherry_planks:'벚나무 판자',
  stick:'막대기', coal:'석탄', charcoal:'숯', iron_ingot:'철 주괴', gold_ingot:'금 주괴', copper_ingot:'구리 주괴', diamond:'다이아몬드', emerald:'에메랄드', redstone:'레드스톤 가루', lapis_lazuli:'청금석', quartz:'네더 석영',
  apple:'사과', bread:'빵', cooked_beef:'스테이크', beef:'생소고기', cooked_porkchop:'익힌 돼지고기', porkchop:'생돼지고기', cooked_chicken:'익힌 닭고기', chicken:'생닭고기',
  wheat:'밀', wheat_seeds:'밀 씨앗', potato:'감자', baked_potato:'구운 감자', carrot:'당근', torch:'횃불', crafting_table:'제작대', furnace:'화로', chest:'상자', hopper:'호퍼',
  arrow:'화살', bow:'활', crossbow:'쇠뇌', shield:'방패', iron_sword:'철 검', diamond_sword:'다이아몬드 검', iron_pickaxe:'철 곡괭이', diamond_pickaxe:'다이아몬드 곡괭이',
  water_bucket:'물 양동이', bucket:'양동이', honeycomb:'벌집 조각', honey_bottle:'꿀병', bookshelf:'책장', paper:'종이', book:'책', leather:'가죽'
};
const CUSTOM_ITEM_NAME={
  "archer_arrow":"§a궁수 전용 화살",
  "archer_boom":"§a[궁수] 폭발 화살",
  "archer_bow":"§a궁수 전용활",
  "archer_triple":"§a[궁수] 트리플 샷",
  "archer_ult":"§a[궁수] 백발백중",
  "archer_wire":"§a[궁수] 와이어 화살",
  "assassin_dagger":"§8암살자 전용 단검",
  "assassin_gas":"§2[암살자] 독기체 암살",
  "assassin_move":"§8[암살자] 암살 이동",
  "assassin_prep":"§8[암살자] 암살 준비",
  "assassin_ult":"§4[암살자] 단체 암살",
  "berserker_axe":"§4광전사 전용 손도끼",
  "berserker_rage":"§4[광전사] 광전사의 분노",
  "berserker_slam":"§c[광전사] 내려찍기",
  "berserker_tornado":"§4[광전사] 토네이도",
  "berserker_ult":"§4[광전사] 미쳐 날뛰기",
  "cleric_bible":"§f성직자 전용 성경책",
  "cleric_prayer":"§e[성직자] 성스러운 기도",
  "cleric_recovery":"§e[성직자] 빛의 회복",
  "cleric_shield":"§f[성직자] 빛의 방패",
  "cleric_spear":"§6[성직자] 빛의 창",
  "fighter_burst":"§6[격투가] 붕권",
  "fighter_flurry":"§6[격투가] 난타",
  "fighter_gauntlet":"§6격투가 전용 건틀릿",
  "fighter_limit":"§6[격투가] 한계돌파",
  "fighter_step":"§6[격투가] 순보",
  "hero_courage":"§6[용사] 용맹한 기사의 용기",
  "hero_heart":"§6[용사] 용맹한 전사의 마음",
  "hero_parry":"§b[용사] 패링",
  "hero_smite":"§c[용사] 강타",
  "hero_sword":"§b용사 전용검",
  "mage_fireball":"§d[마법사] 파이어볼",
  "mage_shield":"§b[마법사] 물의 방패",
  "mage_staff":"§d마법사 전용 마법 지팡이",
  "mage_thunder":"§5[마법사] 천둥번개",
  "mage_vine":"§2[마법사] 가시덩쿨",
  "reaper_absorb":"§5[사신] 영혼 흡수",
  "reaper_ambush":"§c[사신] 사신의 복병",
  "reaper_judgment":"§4§l[사신] 사신의 심판",
  "reaper_massacre":"§4[사신] 사신의 학살",
  "reaper_scythe":"§4사신의 대낫",
  "reaper_soul_100":"§8§l[테스트] 영혼 결정 §c100",
  "sheriff_bullet":"§f리볼버 탄환",
  "sheriff_bullet_bundle":"§6리볼버 묶음 탄약 §7(6발)",
  "sheriff_deadeye":"§5[보안관] 데드 아이",
  "sheriff_enhance":"§e[보안관] 리볼버 강화",
  "sheriff_quickdraw":"§6[보안관] 속사",
  "sheriff_revolver":"§6보안관 리볼버",
  "sheriff_rope":"§e[보안관] 끈",
  "subspace":"§5아공간",
  "sun_guard":"§0[INTERNAL] Sun Guard",
  "sword_dash":"§c[검사] 풍찰만리",
  "sword_draw":"§c[검사] 발도술",
  "sword_rise":"§c[검사] 풍운승천",
  "sword_ult":"§c[검사] 풍흔만리",
  "warrior_sword":"§c검사 전용검"
};
const ITEM_ICON_MAP={
  barrel:"textures/ui/geumyi_subspace_barrel",
  archer_arrow:"textures/items/archer_arrow",
  archer_boom:"textures/items/archer_boom",
  archer_bow:"textures/items/archer_bow",
  archer_triple:"textures/items/archer_triple",
  archer_ult:"textures/items/archer_ult",
  archer_wire:"textures/items/archer_wire",
  assassin_dagger:"textures/items/assassin_dagger",
  assassin_gas:"textures/items/assassin_gas",
  assassin_move:"textures/items/assassin_move",
  assassin_prep:"textures/items/assassin_prep",
  assassin_ult:"textures/items/assassin_ult",
  berserker_axe:"textures/items/berserker_axe",
  berserker_rage:"textures/items/berserker_rage",
  berserker_slam:"textures/items/berserker_slam",
  berserker_tornado:"textures/items/berserker_tornado",
  berserker_ult:"textures/items/berserker_ult",
  cleric_bible:"textures/items/cleric_bible",
  cleric_prayer:"textures/items/cleric_prayer",
  cleric_recovery:"textures/items/cleric_recovery",
  cleric_shield:"textures/items/cleric_shield",
  cleric_spear:"textures/items/cleric_spear",
  fighter_burst:"textures/items/fighter_burst",
  fighter_flurry:"textures/items/fighter_flurry",
  fighter_gauntlet:"textures/items/fighter_gauntlet",
  fighter_limit:"textures/items/fighter_limit",
  fighter_step:"textures/items/fighter_step",
  hero_courage:"textures/items/hero_courage",
  hero_heart:"textures/items/hero_heart",
  hero_parry:"textures/items/hero_parry",
  hero_smite:"textures/items/hero_smite",
  hero_sword:"textures/items/hero_sword",
  mage_fireball:"textures/items/mage_fireball",
  mage_shield:"textures/items/mage_shield",
  mage_staff:"textures/items/mage_staff",
  mage_thunder:"textures/items/mage_thunder",
  mage_vine:"textures/items/mage_vine",
  reaper_absorb:"textures/items/reaper_absorb",
  reaper_ambush:"textures/items/reaper_ambush",
  reaper_judgment:"textures/items/reaper_judgment",
  reaper_massacre:"textures/items/reaper_massacre",
  reaper_scythe:"textures/items/reaper_scythe",
  reaper_soul_100:"textures/items/reaper_absorb",
  sheriff_bullet:"textures/items/sheriff_bullet",
  sheriff_bullet_bundle:"textures/items/sheriff_bullet_bundle",
  sheriff_deadeye:"textures/items/sheriff_deadeye",
  sheriff_enhance:"textures/items/sheriff_enhance",
  sheriff_quickdraw:"textures/items/sheriff_quickdraw",
  sheriff_revolver:"textures/items/sheriff_revolver",
  sheriff_rope:"textures/items/sheriff_rope",
  subspace:"textures/items/subspace",
  // Internal sunlight guard intentionally has no in-game item icon; use a safe UI fallback only.
  sun_guard:"textures/ui/geumyi_subspace_unknown",
  sword_dash:"textures/items/sword_dash",
  sword_draw:"textures/items/sword_draw",
  sword_rise:"textures/items/sword_rise",
  sword_ult:"textures/items/sword_ult",
  warrior_sword:"textures/items/warrior_sword",
  sheriff_bullet:'textures/items/sheriff_bullet', sheriff_bullet_bundle:'textures/items/sheriff_bullet_bundle',
  beehive:'textures/blocks/beehive_side', dirt:'textures/blocks/dirt', grass_block:'textures/blocks/grass_side_carried', stone:'textures/blocks/stone', cobblestone:'textures/blocks/cobblestone', andesite:'textures/blocks/stone_andesite', diorite:'textures/blocks/stone_diorite', granite:'textures/blocks/stone_granite',
  sand:'textures/blocks/sand', red_sand:'textures/blocks/red_sand', gravel:'textures/blocks/gravel', clay:'textures/blocks/clay', oak_log:'textures/blocks/log_oak', spruce_log:'textures/blocks/log_spruce', birch_log:'textures/blocks/log_birch', jungle_log:'textures/blocks/log_jungle', acacia_log:'textures/blocks/log_acacia', dark_oak_log:'textures/blocks/log_big_oak',
  oak_planks:'textures/blocks/planks_oak', spruce_planks:'textures/blocks/planks_spruce', birch_planks:'textures/blocks/planks_birch', jungle_planks:'textures/blocks/planks_jungle', acacia_planks:'textures/blocks/planks_acacia', dark_oak_planks:'textures/blocks/planks_big_oak', cherry_planks:'textures/blocks/planks_cherry', mangrove_planks:'textures/blocks/planks_mangrove',
  stick:'textures/items/stick', coal:'textures/items/coal', charcoal:'textures/items/coal', iron_ingot:'textures/items/iron_ingot', gold_ingot:'textures/items/gold_ingot', copper_ingot:'textures/items/copper_ingot', diamond:'textures/items/diamond', emerald:'textures/items/emerald', redstone:'textures/items/redstone_dust', lapis_lazuli:'textures/items/dye_powder_blue', quartz:'textures/items/quartz',
